### ISSUE TITLE
Bootstrap 3 regressions

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#6063]
Let's collect the regressions introduced by the Bootstrap 3 port in this issue.

* [ ] Scroll bar for "to" input in conversations view (Chromium 43.0.2357.65) screenshots: [[1]](https://cloud.githubusercontent.com/assets/3798614/7995910/f632ffde-0b1a-11e5-8b6d-85bfb93ab990.png)
  [[2]](https://cloud.githubusercontent.com/assets/3798614/7995909/f630124c-0b1a-11e5-80c0-f8a41644544c.png)
* [ ] Avatars in conversation view hidden (Chromium 43.0.2357.65) [screenshot](https://cloud.githubusercontent.com/assets/3798614/7995927/3bf331b0-0b1b-11e5-9ba7-ca94f665dae6.png)
* [x] The dropdown aspect and the "mark as read" icon are too close to the right of the screen on the notification page. ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109179380)) ([commit](https://github.com/diaspora/diaspora/commit/7b7700b31722371118b0bfa2eb8c2314b56796a4))
* [x] The dropdown to add a tag in the left side bar of the stream is misplaced (gap between it and the input) ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109179380)) ([commit](https://github.com/diaspora/diaspora/commit/7b7700b31722371118b0bfa2eb8c2314b56796a4))
* [x] Avatars of people who likes are collapsed in the stream view ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109180187)) ([commit](https://github.com/diaspora/diaspora/commit/7b7700b31722371118b0bfa2eb8c2314b56796a4))
* [x] Images post by link are cropped ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109210968)) ([commit](https://github.com/diaspora/diaspora/commit/39fe6bfff231458aca2f4b075e870675bc369c3f))
* [x] No more animation when uploading an image ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109210968))
* [x] Stream view and notifications view are not as wide as they were on mobile view. ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109212095))
* [x] notifications content lacks padding (mobile) ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109212095))
* [x] Cancel button of "Change password" lacks margin on mobile view for small screens ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109212482))
* [x] Avatar lacks left margin on on contacts page for mobile view. ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109212748))
* [x] Player button for oEmbed content has not the right height ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109354617))
* [x] SPV for reshared posts is broken ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109450895))
* [x] loading spinner broken in streams ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109581123))
* [x] overflow on #tag pages #6142 
* [x] loading spinner for location input in publisher is too big
* [x] Formatting of ignored users in settings -> privacy has broken - used to be one user per line, now they just pile up one after another in the same paragraph. #6349
* [ ] Mobile bookmarklet service icons opacity is the same whether clicked or not ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-128135786))
* [x] Photo viewer doesn't scale photo to screen size ([comment](https://github.com/diaspora/diaspora/issues/6063#issuecomment-128142946)) #6301
* [ ] On the settings page we have a `.container-fluid` div inside of a `.container-fluid` div
* [x] Commenting on stream posts on mobile causes comment not to be loaded properly ([comment and screenshots](https://github.com/diaspora/diaspora/issues/6063#issuecomment-139368965))

**Comment by Flaburgan** [comment]
[ ] The dropdown aspect and the "mark as read" icon are too close to the right of the screen on the notification page.

![capture du 2015-06-04 23 42 25](https://cloud.githubusercontent.com/assets/930064/8000831/a1526a8c-0b5f-11e5-88a2-23f7221a60d1.png)

[ ] The dropdown to add a tag in the left side bar of the stream is misplaced (gap between it and the input)

![capture du 2015-06-05 00 44 49](https://cloud.githubusercontent.com/assets/930064/8000853/eac1670e-0b5f-11e5-8a86-3ef14573cb84.png)

Both problem with Firefox stable.

**Comment by Flaburgan** [comment]
Avatars of people who likes are collapsed in the stream view:
![capture du 2015-06-05 08 53 58](https://cloud.githubusercontent.com/assets/930064/8000910/97ec9354-0b60-11e5-8919-243c68697ce0.png)

**Comment by SansPseudoFix** [comment]
Images post by link are cropped:

![bs3_diaspora_img_crop](https://cloud.githubusercontent.com/assets/6507951/8002866/72b55ff0-0b72-11e5-95c6-dc22be915010.png)

Expected:

![bs3_diaspora_img_crop_expected](https://cloud.githubusercontent.com/assets/6507951/8002871/7f4364ba-0b72-11e5-96d4-9619bdad7273.png)

---

No more animation when upload image:

![bs3_no_animation_upload_img](https://cloud.githubusercontent.com/assets/6507951/8002877/929e7072-0b72-11e5-8119-bf815087837d.png)

**Comment by AugierLe42e** [comment]
Stream view and notifications view are not as wide as they were.

![
](https://cloud.githubusercontent.com/assets/3429231/8002959/43f7faa0-0b73-11e5-8bea-ec5fda909ddd.png)
![](https://cloud.githubusercontent.com/assets/3429231/8002960/43f8cb56-0b73-11e5-8588-136569828a67.png)

And notifications content lacks padding.

**Comment by AugierLe42e** [comment]
Cancel button of "Change password" lacks margin on mobile view for little screens (320px)

![capture d ecran 2015-06-06 a 11 03 37](https://cloud.githubusercontent.com/assets/3429231/8002980/89bb8c46-0b73-11e5-9204-039189e3a853.png)

**Comment by AugierLe42e** [comment]
Avatar lacks left margin on on contacts page for mobile view.

![](https://cloud.githubusercontent.com/assets/3429231/8002989/a1103aae-0b73-11e5-973a-ffcd2b46f918.png)

**Comment by AugierLe42e** [comment]
I think `newcommer` label can be added to this issue ;)

**Comment by AugierLe42e** [comment]
About [this one](https://github.com/diaspora/diaspora/issues/6063#issuecomment-109210968), use [`img-responsive`](http://getbootstrap.com/css/#images-responsive) classe where nessessary.

In general, please avoid adding CSS and prefer using Bootstrap's classes.

**Comment by svbergerem** [comment]
> Images post by link are cropped

This is already fixed on develop.

**Comment by AugierLe42e** [comment]
BTW, there really should be a spec to follow for contributors because HTML and CSS are a mess. Something like a good practice guide. I have a idea or to, just throwing here for now. E.g : every CSS classe should use dash, not camel or snake case. And we definitely should seperate classes used for selecting in JS from these used for CSS. An idea should be that no HTML class used to select in JS should have any CSS rule and should be clearly distinct from CSS customization class by a prefix for instance. Any class starting with `js-` for instance should be only used for JS operations while anything else should be used for CSS rules. It would easy the the refactor preccess by preventing to remove break JS logic whil removing useless or deprecated class. Just saying.

**Comment by jhass** [comment]
@AugierLe42e can you try to not add random stuff to random issues? Your last comment belongs to https://www.loomio.org/d/bLH78pEh/styleguides

**Comment by AugierLe42e** [comment]
Player button for oEmbed content has not the right height:

![player](https://cloud.githubusercontent.com/assets/3429231/8010454/9444908a-0bb0-11e5-874e-027ae32b12ac.png)

Just change [height](https://github.com/diaspora/diaspora/blob/develop/app/assets/stylesheets/_mixins.scss#L73) to `70px`.

**Comment by AugierLe42e** [comment]
Ow... Crapy crap... Didn't see that one coming. :/
Reshared posts are complitely broken:

![](https://cloud.githubusercontent.com/assets/3429231/8016020/9b2488dc-0bde-11e5-95bf-8fccaaa07bcc.png)

**Comment by Flaburgan** [comment]
The loading spinner is not the good one, is too big in notification panel, and broken on the stream page.

![notif](https://cloud.githubusercontent.com/assets/930064/8019868/99682202-0c64-11e5-91fc-97ea7fe81fd0.png)

**Comment by AugierLe42e** [comment]
Nope, it's the same. It's just that there was a duplicate gif of this spinner. The previous one was an ugly low-quality which I suppressed. Just resize this one, it will be ok.

**Comment by Flaburgan** [comment]
At least the stream loading spinner was an arrow: https://github.com/diaspora/diaspora/blob/master/app/assets/images/static-loader.png

**Comment by AugierLe42e** [comment]
Yes, and it was not intended to. If you look at the [infinite scroll widget](https://github.com/diaspora/diaspora/blob/develop/app/assets/javascripts/widgets/infinite-scroll.js) you'll see that the image had to be the spinner.

The only reason an arrow was dispayed is because it was overriden by [a CSS rule](https://github.com/diaspora/diaspora/blob/432f99e0018adbd2032d42e03a1e071325e2a27a/app/assets/stylesheets/new_styles/_spinner.scss#L20). And, according to the `animation` rule, the spinner should have *spinned*. So, actually, that arrow which never moved, was more a bug than something else.

**Comment by Flaburgan** [comment]
The arrow moved, and looked way better that the actual one imo. But this is design not a bug anymore so I'm fine with dealing about it elsewhere than here.

**Comment by AugierLe42e** [comment]
> The arrow moved

I've nerver seen it move... Neither on Forefox nor on Chrome. :/
Anyway, I've just fixed sizes here ;)

**Comment by svbergerem** [comment]
> Cancel button of "Change password" lacks margin

This is the only cancel button on that page. I think we can just remove it.

**Comment by Flaburgan** [comment]
+1 on this Steffen

**Comment by AugierLe42e** [comment]
> Images post by link are cropped

Same thing on images posted in comments and in the biography on profile page. I think the function that generate images should be overriden to automatically add class `img-responsive` on all images.

**Comment by Flaburgan** [comment]
I think I would like to add to the problem list the flat buttons, especially the white ones. Two confusing examples are the log in page where the button really looks like an input field, and the publisher, where it's hard to tell if the "preview" button is enabled or not (check the difference when the publisher is empty and filled).

This is not about design but really about user experience.

**Comment by AugierLe42e** [comment]
I think that problem coul be solved using the material design specification from Google.

**Comment by RichKavanagh** [comment]
So I'm confused now. Should the spinner actually spin when loading the next stream posts and when searching for a user?

**Comment by AugierLe42e** [comment]
Yep. It's now this one:

![](https://github.com/diaspora/diaspora/blob/145aac4d2805eae332bd439c98a067b60c150668/app/assets/images/ajax-loader2.gif?raw=true). But only on BS3 version which is planed for 0.6 not 0.5.1.

**Comment by jaywink** [comment]
* [ ] Formatting of ignored users in settings -> privacy has broken - used to be one user per line, now they just pile up one after another in the same paragraph.

**Comment by jaywink** [comment]
Added: **Mobile bookmarklet service icons opacity is the same whether clicked or not** to the list in the OP. Before icons used to be "less colourful" when not clicked and fully coloured when clicked. See screenshots of no difference at all between clicked and not clicked. In the second image I clicked on Twitter and the remaining chars count appears (though wrong but that is another issue ;)).

![20150805205759](https://cloud.githubusercontent.com/assets/1174866/9096863/9c803cac-3bc8-11e5-815b-ab2b2daa8c42.jpg)
![20150805205814](https://cloud.githubusercontent.com/assets/1174866/9096865/9f4f0756-3bc8-11e5-9659-00a3831f0cf6.jpg)

**Comment by jaywink** [comment]
Added **Photo viewer doesn't scale photo to screen size**, basically this happens when I view a larger-than-my-mobile-screen photo in desktop mode on my mobile browser:

![](http://i.imgur.com/ToeIG6Xl.jpg)

Couldn't see the same on same mobile browser on joindiaspora running 0.5.

**Comment by svbergerem** [comment]
> Couldn't see the same on same mobile browser on joindiaspora running 0.5.

Geraspora (0.5.2.0) with Firefox dev tools testing a screen size of 320x480px:

![photo viewer stable](https://cloud.githubusercontent.com/assets/3798614/9097793/11c85fba-3bc6-11e5-9d63-60f528dc4742.png)

**Comment by AugierLe42e** [comment]
Rails's `image_tag` should be overloaded to always add BS3's `img-responsive` class.

**Comment by jaywink** [comment]
Commenting on posts on mobile on streams (not spv) causes the UI to load the whole site it seems as the result into where the comment should come, instead of the comment.

Two gifs to visualize, one on main stream, one on profile stream.

Main stream
![stream_comment_bug](https://cloud.githubusercontent.com/assets/1174866/9799935/e03cd94e-5812-11e5-9b9f-f5c612a720b9.gif)

Profile stream
![profile_comment_bug](https://cloud.githubusercontent.com/assets/1174866/9799943/e4070694-5812-11e5-83e2-1df186518565.gif)

Will add to main post list.

**Comment by AugierLe42e** [comment]
Yep. Same here.
