### ISSUE TITLE
Simplify mention syntax

### ISSUE THREAD

**Issue by svbergerem** [diaspora/diaspora#7276]
Currently our syntax looks like this: `@{FirstName LastName; user@pod.tld}`.
I'd like to change this to `@{user@pod.tld}` and display the name from the person object. This would fix #3526.

This would also make mentions in the publisher a lot easier since the syntax is easy enough to expose it to our users. So instead of having some overlay for the textarea that adds a blue background to the mentioned name and having to distinguish between the “real” value of the textarea (including the mention syntax) and the “fake” value that only shows the name, we could just display the actual textarea. We still have the preview so users can see the rendered markdown.

I talked about this with @SuperTux88 and we also talked about the needed federation changes. What we came up with is adding support for the new syntax (display, create notifications, etc.) but still converting everything to the old syntax when saving the post/comment. As soon as enough pods support the new syntax we could start saving and sending mentions with the new syntax. These changes would be documented in the federation gem.

We also talked with @annando about this, so he also knows that there might be some changes and he didn't see any problems for friendica. (Given that we announce the changes which we would definitely do.)

I played with the new syntax in the develop branch of the markdown-it-diaspora-mention plugin and now it already supports the new syntax: https://github.com/diaspora/markdown-it-diaspora-mention/commit/52281e10d6811bd6a8344bf29104e14d289e6c9d

### TODOs:

- [x] support new syntax in `markdown-it-diaspora-mention` #7277
- [x] support new syntax in backend (and convert to old syntax for backward compatibility) #7300,  #7305
- [x] simplify publisher and use new syntax #7302
- [ ] remove syntax-backporting in the backend (should be done after most pods support the new syntax)

**Comment by cmrd-senya** [comment]
I would prefer, that along with the new syntax we keep a support of the old one, so that some more advanced users could use it to mention a person with any string as a display name. It is useful in some cases. For example, in inflectional languages the word ending changes in non-nominative case. If you say in Russian "I met Senya today", you'll have to change Senya to "Senyu". Most of the social networks ignore that, and people mention other users in nominative case all the time, which looks and feels very weird. People are getting used to it, but only because they've got no choice. But we aren't them, so we can leave this possibility.

**Comment by svbergerem** [comment]
I never said that we should drop the old syntax. ;) All I'd drop is that overlay in the publisher displaying the user's name.

**Comment by Flaburgan** [comment]
:D Strangely I had the exact same thought about the mention being the only thing wysiwyg in the publisher "write" tab. I approve this idea, however we should be careful about how the UX becomes, because this can be seen as a regression by users.

**Comment by denschub** [comment]
I've heard complaints from users about not being able to move and copy/paste mentions, and using a simplified syntax would solve this issue. +1

**Comment by svbergerem** [comment]
I just want to add another advantage of these changes: they would most probably fix our flaky mentioning cukes: https://travis-ci.org/diaspora/diaspora/jobs/194766148#L1703 (Since there would be just one textarea and no “fake” textarea anymore)

**Comment by denschub** [comment]
What are you waiting for??? :p

**Comment by Flaburgan** [comment]
So, the last task left on this issue is *"remove syntax-backporting in the backend (should be done after most pods support the new syntax)"*. Is that fine if I add the 0.8.0.0 milestone to that issue? Also, the "newcomer" label as this is only stripping, it should not be very complicated?
